"""init

Revision ID: 05c4dd22a80f
Revises: 
Create Date: 2021-09-14 20:54:16.708000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "05c4dd22a80f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moodlebot_telegram_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "moodlebot_micorosft_oidc_credentials",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=500), nullable=True),
        sa.Column("password", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["telegram_user_id"],
            ["moodlebot_telegram_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("moodlebot_micorosft_oidc_credentials")
    op.drop_table("moodlebot_telegram_users")
    # ### end Alembic commands ###
